version: '3.8'

services:
  discord-bot:
    build: .
    container_name: camp-discord-bot
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'
